spring:
  kafka:
    bootstrap-servers: localhost:9092  # Kafka server address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
