spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: analytics
    password: analytics
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
